### ISSUE TITLE
Initial screening for applying for this project

### ISSUE THREAD

**Issue by dinakajoy** [Pocket/curation-tools-frontend#23]
# Tasks

## Submit a screenshot of this component rendered in a browser.

**Comment by olliso17** [comment]
![IMG_0618](https://user-images.githubusercontent.com/61994837/95864989-81b12080-0d3c-11eb-8d55-ae432737c3a8.jpg)
screenshot of a demo app using create react app and material ui

**Comment by LavellTheDev** [comment]
Hello, just wanted to post my screenshot here before I emailed it to the mentors. I thought I would add an extra component just so it would stand out a little more. Thanks :) 

![Screenshot_2020-10-14 React App](https://user-images.githubusercontent.com/36236491/96022587-12f8c380-0e1f-11eb-8e3e-ae78fa15388e.png)
