### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by lape15** [Pocket/curation-tools-frontend#3]
![screenshot-localhost_3000-2020 10 07-19_20_28](https://user-images.githubusercontent.com/50051435/95374962-e3a1fe00-08d6-11eb-9f0b-162d7c9a5007.png)
Hello  everyone
I am an outreachy applicant finding it difficult to submit my initial screening exercise and join the slack group.
Any helped that can be offered is need please.

**Comment by Annettesunday** [comment]
Hey @lape15 

To submit your initial screening exercise, you have to commit your changes, push and create a pull request against the main branch on this  [`repo`](https://github.com/Pocket/curation-tools-frontend)

Concerning the slack error, I am not sure what the solution is. I am getting the error too. If I can find a solution, I will check back with you for an update.

**Comment by LilyLME** [comment]
Hi @lape15 @Annettesunday . Any luck yet?

**Comment by Annettesunday** [comment]
@LilyLME Currently working on the screener exercise. Have you started yet?

**Comment by lape15** [comment]
@Annettesunday Thank you, doing that now
@LilyLME Slack is still the same

**Comment by Adela7** [comment]
Hi everyone,

I believe the opportunity to join the slack group will come at a later stage. 
The project description stated: "You will be invited to our company Slack instance after being accepted."

Hope this helps. 🙂

**Comment by julihdez** [comment]
Hi everyone, I'm also applying, good luck to you all! 
Thanks for the info @Adela7, if anyone gets any updates on the slack joining please let us know over here. 
Thanks 🙂

**Comment by Segun-Ogundipe** [comment]
Hi everyone,

I don't think we are supposed to create a PR for this. The instruction says to submit a screenshot of the rendered component, that doesn't require a PR and it says nothing about how to submit.

**Comment by lape15** [comment]
> Hi everyone,
> 
> I don't think we are supposed to create a PR for this. The instruction says to submit a screenshot of the rendered component, that doesn't require a PR and it says nothing about how to submit.

Exactly why I raised the issue; nonetheless, I still created a pr.

**Comment by Segun-Ogundipe** [comment]
> > Hi everyone,
> > I don't think we are supposed to create a PR for this. The instruction says to submit a screenshot of the rendered component, that doesn't require a PR and it says nothing about how to submit.
> 
> Exactly why I raised the issue; nonetheless, I still created a pr.

Yeah, I get that. It's better to play it safe. The PR was a good call

**Comment by Annettesunday** [comment]
Hey guys, 

I am trying to push my code to the repo to create a PR against it, but I am running into this error.
I have tried changing my git configs but the experience is still the same. Is there something that I am missing?

<img width="713" alt="Screenshot 2020-10-08 at 02 37 09" src="https://user-images.githubusercontent.com/26150162/95398991-d1908180-090f-11eb-9e34-4d986dd5225c.png">

**Comment by Segun-Ogundipe** [comment]
> Hey guys,
> 
> I am trying to push my code to the repo to create a PR against it, but I am running into this error.
> I have tried changing my git configs but the experience is still the same. Is there something that I am missing?
> 
> <img alt="Screenshot 2020-10-08 at 02 37 09" width="713" src="https://user-images.githubusercontent.com/26150162/95398991-d1908180-090f-11eb-9e34-4d986dd5225c.png">

Hi @Annettesunday,

You don't have the permissions necessary to create branches directly in this repo. You'll have to fork the project, create the branch in the forked repo, then create a PR for that branch, Link the PR to this repo

**Comment by Annettesunday** [comment]
@Segun-Ogundipe Thanks. Worked like magic 👏🏾

**Comment by MietVdh** [comment]
Hello all,

Just in case you missed it: the instructions on the Outreachy website have been updated, and now say to submit the screenshot via email.

**Comment by Annettesunday** [comment]
There is a public chat too; this information is available on the Outreachy website as well.
cc @lape15 @LilyLME

**Comment by lape15** [comment]
> There is a public chat too; this information is available on the Outreachy website as well.
> cc @lape15 @LilyLME

Where is the public chat ?

**Comment by lape15** [comment]
> Hello all,
> 
> Just in case you missed it: the instructions on the Outreachy website have been updated, and now say to submit the screenshot via email.

Thank you

**Comment by Ahuoyiza** [comment]
> There is a public chat too; this information is available on the Outreachy website as well.
> cc @lape15 @LilyLME

How do i join the public chat?

**Comment by Annettesunday** [comment]
<img width="1090" alt="Screenshot 2020-10-08 at 21 44 54" src="https://user-images.githubusercontent.com/26150162/95500518-934a9f00-09af-11eb-83df-c312aa3eb658.png">

Check this section of the project description on the Outreachy [site](https://www.outreachy.org/outreachy-december-2020-internship-round/communities/mozilla/#create-user-interface-for-pockets-curated-articles)
It has all the instructions

**Comment by onyeepeace** [comment]
Thanks for updating us here

**Comment by lape15** [comment]
> <img alt="Screenshot 2020-10-08 at 21 44 54" width="1090" src="https://user-images.githubusercontent.com/26150162/95500518-934a9f00-09af-11eb-83df-c312aa3eb658.png">
> 
> Check this section of the project description on the Outreachy [site](https://www.outreachy.org/outreachy-december-2020-internship-round/communities/mozilla/#create-user-interface-for-pockets-curated-articles)
> It has all the instructions

Thank you so much

**Comment by JoyLubega** [comment]
> Hey guys,
> 
> I am trying to push my code to the repo to create a PR against it, but I am running into this error.
> I have tried changing my git configs but the experience is still the same. Is there something that I am missing?
> 
> <img alt="Screenshot 2020-10-08 at 02 37 09" width="713" src="https://user-images.githubusercontent.com/26150162/95398991-d1908180-090f-11eb-9e34-4d986dd5225c.png">

Hey, you are supposed to fork the repo not to push direct to the repo. I also don't think you need to create a PR.

**Comment by jakazzy** [comment]
Sure thank you all fam!

**Comment by ghost** [comment]
Hope the issue has been solved? And I hope you forwarded the screenshot to the emails of the project mentor, as it was specified on their page on the outreach website. That is most important

**Comment by Sunairaa** [comment]
Hey! I have submitted the screenshot to the mentors' email address, do I need to push my code on repo?

**Comment by lape15** [comment]
> Hey! I have submitted the screenshot to the mentors' email address, do I need to push my code on repo?

Hi You don’t need to

**Comment by Sunairaa** [comment]
> > Hey! I have submitted the screenshot to the mentors' email address, do I need to push my code on repo?
> 
> Hi You don’t need to

Thank you for your response! that's mean we have no need to create a PR also?
