### ISSUE TITLE
I'm Unable to make a PR

### ISSUE THREAD

**Issue by ghost** [Pocket/curation-tools-frontend#56]
I have done my first task of making a screenshot of the pocket logo and a button containing my name and I linked my fork of this repo with the local one on my computer and everything works fine. I can see the changes I make. But I can't seem to find the pull request button.
![pocket](https://user-images.githubusercontent.com/56835876/95599671-47e4cf00-0a49-11eb-87f8-07280b175429.jpg)

**Comment by Annettesunday** [comment]
Hey @KarenEfereyan 

The task is to be submitted to the mentors via email. The instructions on the website were updated, and I think you might want to take a look again.

**Comment by Annettesunday** [comment]
That said, though if you still want us to look at this, yes, we can.

**Comment by ghost** [comment]
Thanks Annette.I already submitted to the mentors Email. So I guess im covered. Thanks
