### ISSUE TITLE
Create a header component

### ISSUE THREAD

**Issue by jpetto** [Pocket/curation-tools-frontend#61]
The header component should stretch to fit 100% of the browser width, however, the content in the header should only expand to 1024px wide, centered as in the screenshot below.

Include all elements visible in the screenshot below: Pocket logo, locale specification, New Tab/Content selector, and buttons.

Please follow the instructions in [OUTREACHY.md](https://github.com/Pocket/curation-tools-frontend/blob/main/OUTREACHY.md) when developing the component.

All tasks should be completed using Typescript.

<img width="1160" alt="header" src="https://user-images.githubusercontent.com/317532/96734216-ecd3a600-137f-11eb-8ef7-dff973cf7a63.png">

**Comment by lalidiaz** [comment]
Hi, can I work on this issue please? @jpetto

**Comment by kkyeboah** [comment]
yes please, @lalidiaz, I'll assign this issue to you.

**Comment by lalidiaz** [comment]
thanks!

**Comment by jpetto** [comment]
completed in #73
