### ISSUE TITLE
Create a card component

### ISSUE THREAD

**Issue by jpetto** [Pocket/curation-tools-frontend#62]
Create a card component matching the structure of the screenshot below. The component should have two rows, both broken into two columns: 30% and 70%. Alignment of the elements should match the screenshot.

Please follow the instructions in [OUTREACHY.md](https://github.com/Pocket/curation-tools-frontend/blob/main/OUTREACHY.md) when developing the component.

All tasks should be completed using Typescript.

<img width="1121" alt="card" src="https://user-images.githubusercontent.com/317532/96735707-75067b00-1381-11eb-9c58-6050373243c8.png">

**Comment by Joaquin-M2** [comment]
Hello! Can I try solving this issue?

**Comment by kkyeboah** [comment]
Absolutely @Joaquin-M2, I'll assign this to you

**Comment by jpetto** [comment]
completed in #71
