### ISSUE TITLE
Create a tab navigation component

### ISSUE THREAD

**Issue by jpetto** [Pocket/curation-tools-frontend#63]
Create a tab navigation component that can satisfy the screenshots below. There will either be 2 or 4 tabs. The tabs should take up the entire width of the container. Each tab may have a pill included containing a number.

Please follow the instructions in [OUTREACHY.md](https://github.com/Pocket/curation-tools-frontend/blob/main/OUTREACHY.md) when developing the component. Be sure your demo includes rendering this component both with 4 and 2 tabs, with at least one tab in each instance containing a numbered pill (you can fill the component with any data/text you'd like for demonstration purposes).

All tasks should be completed using Typescript.

<img width="954" alt="tab1" src="https://user-images.githubusercontent.com/317532/96770029-96795e00-13a5-11eb-8a16-b4f1bc0e26a2.png">
<img width="960" alt="tab2" src="https://user-images.githubusercontent.com/317532/96770035-9711f480-13a5-11eb-80e2-6f02edddfcc1.png">
<img width="987" alt="tab3" src="https://user-images.githubusercontent.com/317532/96770036-9711f480-13a5-11eb-8039-3c0f9cfffe52.png">

**Comment by raymond-sikpojie** [comment]
Can I work on this? I'm an Outreachy applicant.

**Comment by Joaquin-M2** [comment]
Since #71 has been reviewed and I updated the PR with the requested modifications, I would like to be assigned to this other issue if that's fine with everyone.
