### ISSUE TITLE
Create a card text component

### ISSUE THREAD

**Issue by jpetto** [Pocket/curation-tools-frontend#64]
Create a card text component to match the screenshot below. 

Please follow the instructions in [OUTREACHY.md](https://github.com/Pocket/curation-tools-frontend/blob/main/OUTREACHY.md) when developing the component.

All tasks should be completed using Typescript.

<img width="989" alt="card-text" src="https://user-images.githubusercontent.com/317532/96771707-a8f49700-13a7-11eb-8257-bcab145b3a84.png">

**Comment by raymond-sikpojie** [comment]
Hey @jpetto can I work on this?

**Comment by jpetto** [comment]
hello @raymond-sikpojie - thank you for your interest! however, we are currently reserving these issues for applicants going through the [outreachy](https://www.outreachy.org/) process. this project will be dedicated to outreachy through march of 2021. hopefully pocket will be open sourcing more repositories in the near future. keep an eye out!

**Comment by nina-py** [comment]
Hi @jpetto , can I take this one? Also, could you clarify if the screenshot and buttons are part of the component, or just the elements circled in teal?

**Comment by nina-py** [comment]
Oh, I see that creating the shell of the card component is addressed in this issue: https://github.com/Pocket/curation-tools-frontend/issues/62. That means this one is definitely only for the text part.

**Comment by raymond-sikpojie** [comment]
I'm actually an outreachy candidate @jpetto

**Comment by jpetto** [comment]
@raymond-sikpojie apologies for the confusion - we've received over 80 applications via outreachy, and have closed our project to further applications. out of the initial applicants, we have selected only a handful to make it to the next round. these issues are reserved for those few who have made it to the next round.
