### ISSUE TITLE
Create a login page

### ISSUE THREAD

**Issue by jpetto** [Pocket/curation-tools-frontend#65]
Create a login page matching the screenshot below.

Please follow the instructions in [OUTREACHY.md](https://github.com/Pocket/curation-tools-frontend/blob/main/OUTREACHY.md) when developing the component.

All tasks should be completed using Typescript.

<img width="957" alt="login" src="https://user-images.githubusercontent.com/317532/96786138-718ce700-13b5-11eb-8e94-295531a25e9b.png">

**Comment by alicendeh** [comment]
Hi @jpetto  can I work on this please ?

**Comment by kkyeboah** [comment]
Yes, you can @alicendeh

**Comment by alicendeh** [comment]
Thanks

**Comment by jpetto** [comment]
completed in #79
