### ISSUE TITLE
Create add story page component

### ISSUE THREAD

**Issue by jpetto** [Pocket/curation-tools-frontend#66]
Create an add story page component matching the screenshot below. The header in the screenshot should be ignored (and will be completed in a separate issue).

The contents of this page should fill 100% of the available width. There is a separate issue to create the wrapper that will constrain the width and center the content on the page. For this issue, it is expected that the content will span the full width of the browser (and will later be width-constrained when integrated with the wrapper component).

Please follow the instructions in [OUTREACHY.md](https://github.com/Pocket/curation-tools-frontend/blob/main/OUTREACHY.md) when developing the component.

All tasks should be completed using Typescript.

<img width="1138" alt="add-story" src="https://user-images.githubusercontent.com/317532/96880043-57e5b100-1442-11eb-8126-dae0f15c2c00.png">

**Comment by alicendeh** [comment]
Hi can I work on this @jpetto

**Comment by mhtien** [comment]
May I take this issue? 😄

**Comment by kkyeboah** [comment]
Of course, @mhtien

**Comment by jpetto** [comment]
completed in #76
