### ISSUE TITLE
Create a modal loading component

### ISSUE THREAD

**Issue by jpetto** [Pocket/curation-tools-frontend#67]
Create a component that will display a modal over the screen. The purpose of this modal will be to display an image and a short amount of text (that should be passed in as props) to give the user information while data is loading or being processed.

For example, in the screenshot below, clicking the "Parse" button will trigger an AJAX request, and should display an instance of this modal component while that request is processing.

Please follow the look and feel of the screenshot below, but also get creative!

Please follow the instructions in [OUTREACHY.md](https://github.com/Pocket/curation-tools-frontend/blob/main/OUTREACHY.md) when developing the component.

All tasks should be completed using Typescript.

<img width="1153" alt="modal" src="https://user-images.githubusercontent.com/317532/96881405-dabb3b80-1443-11eb-8d87-f07d47ca3011.png">

**Comment by qmya** [comment]
Hi @jpetto Can I work on it?

**Comment by qmya** [comment]
Hi, @kkyeboah Could you assign me this one :) Thanks

**Comment by qmya** [comment]
Hi @kkyeboah could I work on this 😀

**Comment by jpetto** [comment]
completed in #82
