### ISSUE TITLE
Create a button component

### ISSUE THREAD

**Issue by jpetto** [Pocket/curation-tools-frontend#68]
Create a button component that can render all of the button possibilities in the screenshots below. As props, the component should accept:

- text to display
- size: ~normal, large (should default to normal)~ **[ updated to use Material UI sizes ]** small, medium, large (should default to medium)
- type: positive (solid green), negative (solid red/brown), neutral (solid grey), hollow (white with green border).

Each type should have a subtle hover state (get creative!).

Please follow the instructions in [OUTREACHY.md](https://github.com/Pocket/curation-tools-frontend/blob/main/OUTREACHY.md) when developing the component. Be sure to include all size and type variations in your demo!

All tasks should be completed using Typescript.

<img width="1050" alt="buttons" src="https://user-images.githubusercontent.com/317532/96883024-85802980-1445-11eb-9ad1-fc2cda26bd82.png">

**Comment by qmya** [comment]
Hey, @jpetto Can I work on this?

**Comment by jpetto** [comment]
@qmya okay, this one is yours!

**Comment by qmya** [comment]
💃

**Comment by jpetto** [comment]
completed in #83
