### ISSUE TITLE
Create edit and approve page component

### ISSUE THREAD

**Issue by jpetto** [Pocket/curation-tools-frontend#70]
Create an Edit & Approve page component matching the screenshot below. The header in the screenshot should be ignored (and will be completed in a separate issue). Also note the screenshot is incorrect - the white page background should extend the full height.

The contents of this page should fill 100% of the available width. There is a separate issue to create the wrapper that will constrain the width and center the content on the page. For this issue, it is expected that the content will span the full width of the browser (and will later be width-constrained when integrated with the wrapper component).

Please follow the instructions in [OUTREACHY.md](https://github.com/Pocket/curation-tools-frontend/blob/main/OUTREACHY.md) when developing the component.

All tasks should be completed using Typescript.

<img width="1148" alt="edit-and-approve" src="https://user-images.githubusercontent.com/317532/96884764-7d28ee00-1447-11eb-8436-44e6cbefc41e.png">

**Comment by alicendeh** [comment]
Hi @jpetto  and @kkyeboah please can I work on this issue while you guys are reviewing the PRs?

**Comment by alicendeh** [comment]
Based on what @kkyeboah said I’ll go ahead an work on this issue

**Comment by jpetto** [comment]
@alicendeh are you still interested in completing this issue? i believe you were very close!
