### ISSUE TITLE
create prospects page - first tab/view only (first use of API)

### ISSUE THREAD

**Issue by jpetto** [Pocket/curation-tools-frontend#96]
create the prospects page as detailed in the [figma comps](https://www.figma.com/file/J3D7KOV97p0EsykJUCDL7U/Curation-Tools?node-id=1498%3A30&viewport=0%2C0%2C1).

the goals of this issue are:

1. create the basic layout/UI of the prospects page, but only focus on the first tab ("Prospects" in the figma comp)
2. figure out how to call the API - a simple query retrieving all prospects (the locale can be hard-coded for this issue to keep things simple)

API access details will be provided privately via slack.

**Comment by nina-py** [comment]
New dependencies:

```bash
npm install aws-appsync-auth-link aws-appsync-subscription-link graphql @apollo/client
```
